<a href="https://colab.research.google.com/github/ChaeHyunIM/Helloworld/blob/main/day11_%EC%98%A4%ED%9B%84%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
np33

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240]])

In [ ]:
np333=np33.reshape(2,3,4)

In [ ]:
np333

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]],

       [[130, 140, 150, 160],
        [170, 180, 190, 200],
        [210, 220, 230, 240]]])

In [ ]:
np333.ndim

3

In [ ]:
np333.shape

(2, 3, 4)

In [ ]:
np333[0,0,2]

30

In [ ]:
np333[0,2,:]

array([ 90, 100, 110, 120])

In [ ]:
np333[1,1:,0:2]

array([[170, 180],
       [210, 220]])

In [ ]:
np333[0,1:,2:], np333[1,:2,2:]

(array([[ 70,  80],
        [110, 120]]), array([[150, 160],
        [190, 200]]))

In [ ]:
np333[:,:,2:]

array([[[ 30,  40],
        [ 70,  80],
        [110, 120]],

       [[150, 160],
        [190, 200],
        [230, 240]]])

In [ ]:
np334=np333[:,:,2:]

In [ ]:
np334

array([[[ 30,  40],
        [ 70,  80],
        [110, 120]],

       [[150, 160],
        [190, 200],
        [230, 240]]])

In [ ]:
np.delete(np334[1,:,:],2,0)

array([[150, 160],
       [190, 200]])

In [ ]:
a1=np333[0,1:,2:]

In [ ]:
a2=np333[1,:2,2:]

In [ ]:
np.r_[a1,a2]

array([[ 70,  80],
       [110, 120],
       [150, 160],
       [190, 200]])