<a href="https://colab.research.google.com/github/ChaeHyunIM/Helloworld/blob/main/day12_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
n1 = np.random.randint(0,100,10)

In [4]:
n1

array([58, 32, 57, 40, 85, 62, 15, 54, 98, 84])

In [6]:
type(n1)

numpy.ndarray

In [7]:
n1.shape

(10,)

In [8]:
n1.size

10

In [9]:
n1.nbytes

80

In [11]:
n1.itemsize

8

In [14]:
n=n1.copy()

In [15]:
n[:]

array([58, 32, 57, 40, 85, 62, 15, 54, 98, 84])

In [16]:
n[0:10]

array([58, 32, 57, 40, 85, 62, 15, 54, 98, 84])

In [18]:
n[0:10:2]

array([58, 57, 85, 15, 98])

In [19]:
n[0:10:3]

array([58, 40, 15, 84])

In [20]:
n[::-1]

array([84, 98, 54, 15, 62, 85, 40, 57, 32, 58])

In [22]:
n[::-2]

array([84, 54, 62, 40, 32])

In [23]:
n.reshape(2,5)

array([[58, 32, 57, 40, 85],
       [62, 15, 54, 98, 84]])

In [24]:
n.sort()

In [25]:
n

array([15, 32, 40, 54, 57, 58, 62, 84, 85, 98])

In [28]:
n.sort(axis=0)

In [29]:
n

array([15, 32, 40, 54, 57, 58, 62, 84, 85, 98])

In [30]:
n2=np.random.randint(1,100, 12)

In [31]:
n2

array([27, 40, 71, 21, 96, 16, 37, 26, 75,  2, 84, 76])

In [32]:
n2.reshape(3,4)

array([[27, 40, 71, 21],
       [96, 16, 37, 26],
       [75,  2, 84, 76]])

In [33]:
n21=np.arange(1,17,dtype=np.int16)

In [34]:
n21

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int16)

In [35]:
n=n21.reshape(4,4)

In [36]:
n[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int16)

In [37]:
n[0,3]

4

In [41]:
n[1:,2:]

array([[ 7,  8],
       [11, 12],
       [15, 16]], dtype=int16)

In [42]:
n[2:,:2]

array([[ 9, 10],
       [13, 14]], dtype=int16)

In [44]:
n[0,1:3]

array([2, 3], dtype=int16)

In [45]:
n[2:,1:3]

array([[10, 11],
       [14, 15]], dtype=int16)

In [46]:
n[0]<5

array([ True,  True,  True,  True])

In [47]:
n[0][0]==100

False

In [48]:
n>10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [49]:
n[0][3]=44

In [50]:
n.sum()

176

In [53]:
n[0].sum()

50

In [55]:
n.max(axis=1)

array([44,  8, 12, 16], dtype=int16)

In [54]:
n.max(axis=0)

array([13, 14, 15, 44], dtype=int16)

In [59]:
np.median(n)

9.5

In [60]:
np.median(n[0])

2.5

In [61]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [62]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [63]:
np.tri(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [65]:
np.empty(6)

array([4.68526185e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

In [66]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [68]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [69]:
np.array([4,5,6,7])

array([4, 5, 6, 7])

In [73]:
n7 = np.array([4,5,6,7])

In [74]:
n8 = np.array([4,5,6,7], np.int32)

In [75]:
n8

array([4, 5, 6, 7], dtype=int32)

In [76]:
k=[i for i in range(5,51,5)]

In [77]:
k

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

In [78]:
type(k)

list

In [79]:
t=(i for i in range(10,101,10))

In [80]:
type(t)

generator

In [81]:
n10=np.array(k)

In [82]:
n10

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [83]:
np.array(t)

array(<generator object <genexpr> at 0x7f3f4fdfc6d0>, dtype=object)

In [89]:
s1=pd.Series([2,4,6,8])

In [90]:
type(s1)

pandas.core.series.Series

In [92]:
s1.shape

(4,)

In [93]:
s1.ndim

1

In [98]:
s1.items

<bound method Series.items of 0    2
1    4
2    6
3    8
dtype: int64>

In [99]:
s1.index

RangeIndex(start=0, stop=4, step=1)

In [96]:
s1

0    2
1    4
2    6
3    8
dtype: int64

In [101]:
s1.index=[['T','K','B','Q']]

In [102]:
s1

T    2
K    4
B    6
Q    8
dtype: int64

In [112]:
s1.iloc[1], s1.iloc[2]

(4, 6)

In [113]:
pd1 = pd.read_csv('/content/sample_data/california_housing_test.csv')

In [114]:
type(pd1)

pandas.core.frame.DataFrame

In [115]:
pd1.shape

(3000, 9)

In [116]:
p=pd1.copy()

In [117]:
p

longitude  latitude  ...  median_income  median_house_value
0       -122.05     37.37  ...         6.6085            344700.0
1       -118.30     34.26  ...         3.5990            176500.0
2       -117.81     33.78  ...         5.7934            270500.0
3       -118.36     33.82  ...         6.1359            330000.0
4       -119.67     36.33  ...         2.9375             81700.0
...         ...       ...  ...            ...                 ...
2995    -119.86     34.42  ...         1.1790            225000.0
2996    -118.14     34.06  ...         3.3906            237200.0
2997    -119.70     36.30  ...         2.2895             62000.0
2998    -117.12     34.10  ...         3.2708            162500.0
2999    -119.63     34.42  ...         8.5608            500001.0

[3000 rows x 9 columns]

In [118]:
p.head(3)

longitude  latitude  ...  median_income  median_house_value
0    -122.05     37.37  ...         6.6085            344700.0
1    -118.30     34.26  ...         3.5990            176500.0
2    -117.81     33.78  ...         5.7934            270500.0

[3 rows x 9 columns]

In [210]:
from google.colab import drive

In [211]:
drive.mount('/content/drive')

Mounted at /content/drive


In [212]:
pd2=pd.read_csv('/content/drive/MyDrive/s1.csv', encoding='cp949', header=None)

In [127]:
pd2

0   1   2   3
0  이순신  85  87  90
1  강감찬  75  80  95
2  한석봉  99  98  99
3  황진이  35  45  20
4  안중근  90  85  90
5  박문수  95  98  96
6  임꺽정  15  35  45
7  김정호  90  95  80
8  정몽주  90  90  95
9  임채현  50  45  60

In [128]:
pd2.columns=['이름', '국어', '영어', '수학']

In [129]:
p=pd2.copy()

In [130]:
p

이름  국어  영어  수학
0  이순신  85  87  90
1  강감찬  75  80  95
2  한석봉  99  98  99
3  황진이  35  45  20
4  안중근  90  85  90
5  박문수  95  98  96
6  임꺽정  15  35  45
7  김정호  90  95  80
8  정몽주  90  90  95
9  임채현  50  45  60

In [131]:
p.shape

(10, 4)

In [132]:
type(p)

pandas.core.frame.DataFrame

In [133]:
p.ndim

2

In [135]:
p.size

40

In [136]:
p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   이름      10 non-null     object
 1   국어      10 non-null     int64 
 2   영어      10 non-null     int64 
 3   수학      10 non-null     int64 
dtypes: int64(3), object(1)
memory usage: 448.0+ bytes


In [137]:
p.describe()

국어         영어         수학
count  10.000000  10.000000  10.000000
mean   72.400000  75.800000  77.000000
std    28.883675  24.371203  26.670833
min    15.000000  35.000000  20.000000
25%    56.250000  53.750000  65.000000
50%    87.500000  86.000000  90.000000
75%    90.000000  93.750000  95.000000
max    99.000000  98.000000  99.000000

In [138]:
p.index

RangeIndex(start=0, stop=10, step=1)

In [139]:
p.columns

Index(['이름', '국어', '영어', '수학'], dtype='object')

In [142]:
p['총점']=p['국어']+p['수학']+p['영어']

In [143]:
p['총점']

0    262
1    250
2    296
3    100
4    265
5    289
6     95
7    265
8    275
9    155
Name: 총점, dtype: int64

In [145]:
p['평균']=p['총점']/3

In [146]:
p['평균']

0    87.333333
1    83.333333
2    98.666667
3    33.333333
4    88.333333
5    96.333333
6    31.666667
7    88.333333
8    91.666667
9    51.666667
Name: 평균, dtype: float64

In [188]:
p

이름  국어  영어  수학   총점         평균
0  이순신  85  87  90  262  87.333333
1  강감찬  75  80  95  250  83.333333
2  한석봉  99  98  99  296  98.666667
3  황진이  35  45  20  100  33.333333
4  안중근  90  85  90  265  88.333333
5  박문수  95  98  96  289  96.333333
6  임꺽정  15  35  45   95  31.666667
7  김정호  90  95  80  265  88.333333
8  정몽주  90  90  95  275  91.666667
9  임채현  50  45  60  155  51.666667

In [168]:
p.mean(axis=0)

국어     72.400000
영어     75.800000
수학     77.000000
총점    225.200000
평균     75.066667
dtype: float64

In [157]:
p.mean(axis=1)

0    122.266667
1    116.666667
2    138.133333
3     46.666667
4    123.666667
5    134.866667
6     44.333333
7    123.666667
8    128.333333
9     72.333333
dtype: float64

In [164]:
p.iloc[3,0]

'황진이'

In [165]:
p.loc[:,['이름','수학']]

이름  수학
0  이순신  90
1  강감찬  95
2  한석봉  99
3  황진이  20
4  안중근  90
5  박문수  96
6  임꺽정  45
7  김정호  80
8  정몽주  95
9  임채현  60

In [167]:
p[['이름']]

이름
0  이순신
1  강감찬
2  한석봉
3  황진이
4  안중근
5  박문수
6  임꺽정
7  김정호
8  정몽주
9  임채현

In [171]:
p.iloc[:,1:]>=70

국어     영어     수학    총점     평균
0   True   True   True  True   True
1   True   True   True  True   True
2   True   True   True  True   True
3  False  False  False  True  False
4   True   True   True  True   True
5   True   True   True  True   True
6  False  False  False  True  False
7   True   True   True  True   True
8   True   True   True  True   True
9  False  False  False  True  False

In [174]:
p.loc[:,'국어':]>=70

국어     영어     수학    총점     평균
0   True   True   True  True   True
1   True   True   True  True   True
2   True   True   True  True   True
3  False  False  False  True  False
4   True   True   True  True   True
5   True   True   True  True   True
6  False  False  False  True  False
7   True   True   True  True   True
8   True   True   True  True   True
9  False  False  False  True  False

In [175]:
p?

ValueError: ignored

In [177]:
p.sum()

이름    이순신강감찬한석봉황진이안중근박문수임꺽정김정호정몽주임채현
국어                               724
영어                               758
수학                               770
총점                              2252
평균                           750.667
dtype: object

In [178]:
p.sum(axis=1)

0    611.333333
1    583.333333
2    690.666667
3    233.333333
4    618.333333
5    674.333333
6    221.666667
7    618.333333
8    641.666667
9    361.666667
dtype: float64

In [182]:
p['국어'].value_counts()

90    3
95    1
75    1
15    1
85    1
99    1
50    1
35    1
Name: 국어, dtype: int64

In [183]:
p['국어'].value_counts(ascending=False)

90    3
95    1
75    1
15    1
85    1
99    1
50    1
35    1
Name: 국어, dtype: int64

In [185]:
p['국어'].sort_values(ascending=False)

2    99
5    95
8    90
7    90
4    90
0    85
1    75
9    50
3    35
6    15
Name: 국어, dtype: int64

In [186]:
p.sort_values(by='영어')

이름  국어  영어  수학   총점         평균
6  임꺽정  15  35  45   95  31.666667
3  황진이  35  45  20  100  33.333333
9  임채현  50  45  60  155  51.666667
1  강감찬  75  80  95  250  83.333333
4  안중근  90  85  90  265  88.333333
0  이순신  85  87  90  262  87.333333
8  정몽주  90  90  95  275  91.666667
7  김정호  90  95  80  265  88.333333
2  한석봉  99  98  99  296  98.666667
5  박문수  95  98  96  289  96.333333

In [187]:
p.sort_values(by=['영어', '수학'])

이름  국어  영어  수학   총점         평균
6  임꺽정  15  35  45   95  31.666667
3  황진이  35  45  20  100  33.333333
9  임채현  50  45  60  155  51.666667
1  강감찬  75  80  95  250  83.333333
4  안중근  90  85  90  265  88.333333
0  이순신  85  87  90  262  87.333333
8  정몽주  90  90  95  275  91.666667
7  김정호  90  95  80  265  88.333333
5  박문수  95  98  96  289  96.333333
2  한석봉  99  98  99  296  98.666667

In [198]:
p.sort_values(by=['영어', '수학'], inplace=True)

In [199]:
p

이름  국어  영어  수학   총점         평균
6  임꺽정  15  35  45   95  31.666667
3  황진이  35  45  20  100  33.333333
9  임채현  50  45  60  155  51.666667
1  강감찬  75  80  95  250  83.333333
4  안중근  90  85  90  265  88.333333
0  이순신  85  87  90  262  87.333333
8  정몽주  90  90  95  275  91.666667
7  김정호  90  95  80  265  88.333333
5  박문수  95  98  96  289  96.333333
2  한석봉  99  98  99  296  98.666667

In [195]:
p['영어']+5

6     40
3     50
9     50
1     85
4     90
0     92
8     95
7    100
5    103
2    103
Name: 영어, dtype: int64

In [202]:
p

이름  국어  영어  수학   총점         평균
6  임꺽정  15  35  45   95  31.666667
3  황진이  35  45  20  100  33.333333
9  임채현  50  45  60  155  51.666667
1  강감찬  75  80  95  250  83.333333
4  안중근  90  85  90  265  88.333333
0  이순신  85  87  90  262  87.333333
8  정몽주  90  90  95  275  91.666667
7  김정호  90  95  80  265  88.333333
5  박문수  95  98  96  289  96.333333
2  한석봉  99  98  99  296  98.666667

In [207]:
def get_grade(x):
  grade = ''
  if x >= 90: grade = '수'
  elif x >= 80: grade = '우'
  elif x >= 70: grade = '미'
  elif x >= 60: grade = '양'
  else: grade = '가'
  return grade
p['평가'] = p['평균'].apply(lambda x: get_grade(x))

In [208]:
p

이름  국어  영어  수학   총점         평균 평가
6  임꺽정  15  35  45   95  31.666667  가
3  황진이  35  45  20  100  33.333333  가
9  임채현  50  45  60  155  51.666667  가
1  강감찬  75  80  95  250  83.333333  우
4  안중근  90  85  90  265  88.333333  우
0  이순신  85  87  90  262  87.333333  우
8  정몽주  90  90  95  275  91.666667  수
7  김정호  90  95  80  265  88.333333  우
5  박문수  95  98  96  289  96.333333  수
2  한석봉  99  98  99  296  98.666667  수